### ISSUE TITLE
open_pdks version check should not use git

### ISSUE THREAD

**Issue by proppy** [efabless/mpw_precheck#120]
Since developers might not have a checkout of the open_pdks repo (i.e: if relying on a pre-build PDK), the precheck for `Open PDKs & Skywater PDK versions` should probably rely on the metadata `.config/nodeinfo.json` installed by `open_pdks` instead, as documented in https://github.com/RTimothyEdwards/open_pdks/blob/7791df2b70589399f2e3a4faaeb1a0ba803b84dd/docs.txt#L516

Related https://github.com/The-OpenROAD-Project/OpenLane/issues/923.

**Comment by DavidRLindley** [comment]
I'm closing this ticket due to age and staleness.  The related OpenROAD ticket was closed in March 2022.
