### ISSUE TITLE
Flagging metal4 spacing errors incorrectly

### ISSUE THREAD

**Issue by mguthaus** [efabless/mpw_precheck#131]
In the SRAM macros, the klayout DRC deck is incorrectly flagging an error of:
Metal 4 >3um spacing to unrelated m4 <0.4um.
met4.5b
![image (5)](https://user-images.githubusercontent.com/12450095/176922512-d64d8807-a904-41ca-aeb3-c781929a3750.png)

Example layout:
https://github.com/VLSIDA/sky130_sram_macros/blob/dev/sky130_sram_1kbyte_1rw1r_32x256_8/sky130_sram_1kbyte_1rw1r_32x256_8.gds

**Comment by marwaneltoukhy** [comment]
This is not flagging DRC errors anymore
