### ISSUE TITLE
Incorrect DRC error in klayout with nwell.4

### ISSUE THREAD

**Issue by mguthaus** [efabless/mpw_precheck#132]
The klayout DRC deck is incorrectly flagging an nwell as not having a tap (nwell.4). Example:
![image (6)](https://user-images.githubusercontent.com/12450095/176922838-9984a424-83c0-4e9d-9c34-714bee41d48f.png)

Example layout:
https://github.com/VLSIDA/sky130_sram_macros/blob/dev/sky130_sram_1kbyte_1rw1r_32x256_8/sky130_sram_1kbyte_1rw1r_32x256_8.gds

**Comment by marwaneltoukhy** [comment]
This is not flagging DRC errors anymore
