### ISSUE TITLE
add precheck for connecting user_oeb

### ISSUE THREAD

**Issue by jeffdi** [efabless/mpw_precheck#201]
basic requirement needs to confirm that oeb is connected when user connects to input or output.

**Comment by jeffdi** [comment]
@RTimothyEdwards we need documentation for the gpio block.

**Comment by RTimothyEdwards** [comment]
What form of documentation do you want, and where do you want it to go?  I have plenty of documentation of the GPIO from the original MPW-one documentation that needs only minor updates for the current version.

**Comment by RTimothyEdwards** [comment]
Also note that the documentation for the GF version of the GPIO control block is different from that for the sky130 version, so we will need to make sure that we organize the documentation to make clear which version of the caravel chip the documentation corresponds to, and to make sure that we have proper documentation for both versions (and any future additional versions) of the caravel chip.

**Comment by RTimothyEdwards** [comment]
FYI, the spreadsheet that I made recently for the SPI and wishbone memory maps of the GPIO is only correct for the sky130 version.  When I get the chance, I'll split off a version for GF and make the appropriate changes.  Of course, that's only part of the documentation, but it's a major component of it.

**Comment by jeffdi** [comment]
test developed - needs integration with precheck @marwaneltoukhy.  

need to make extraction standalone.  this should support any user_project_wrapper GDS, regardless of the design flow used to create it.
