### ISSUE TITLE
SPDX COMPLIANCE checks for files in venv and openlane runs

### ISSUE THREAD

**Issue by mo-hosni** [efabless/mpw_precheck#216]
It is more convenient if the SPDX COMPLIANCE check ignore the files in venv and openlane runs because those will always produce errors and these files are not usually pushed on github.

**Comment by marwaneltoukhy** [comment]
It looks like only the `.loc` files are being tagged, along with cocotb files, which will be fixed. Please make sure you're using the latest precheck.
