### ISSUE TITLE
review drc rules and precheck steps currently implemented for GF180

### ISSUE THREAD

**Issue by marwaneltoukhy** [efabless/mpw_precheck#231]

**Comment by marwaneltoukhy** [comment]
Precheck missing checks:

1. LVS
2. OEB
3. Consistency
4. Defaults (makes sure that the readme and gds are different)
5. Documentation (makes sure the documentation is readable and doesn't contain non-inclusive words)
6. Pin label purpose overlapping drawing
7. zero area
8. magic DRC
9. Makefile (makes sure the makefile has the required targets `'check-caravel', 'check-pdk', 'check-precheck', 'clean', 'help', 'install', 'openlane', 'precheck', 'run-precheck', 'simenv', 'simlink', 'uninstall', 'update_caravel', 'verify'`)
10. manifest (makes sure the user is using the correct caravel)

**Comment by marwaneltoukhy** [comment]
DRC rules list:
https://docs.google.com/spreadsheets/d/10AvjBIigrxH9b7_KaqSEuhQlGs3enxP4jqt_ax2O9Ek/edit?usp=sharing

**Comment by jeffdi** [comment]
Target for precheck:

- OEB
- defaults
- documentation
- Makefile
- manifest

**Comment by marwaneltoukhy** [comment]
For the OEB we need the tech files for `gf180mcuD`

**Comment by marwaneltoukhy** [comment]
Timing profile on the example project https://docs.google.com/spreadsheets/d/1X5Z1ui3BesCzzAIfZDyxrgVrL7Cjmlfw02ltszCsruI/edit#gid=0

**Comment by marwaneltoukhy** [comment]
Done here #244
