### ISSUE TITLE
need drc check for path spikes

### ISSUE THREAD

**Issue by jeffdi** [efabless/mpw_precheck#264]
Calibre flags drc error for paths that double back on themselves.

![Image](https://github.com/efabless/mpw_precheck/assets/42048757/89099702-22f0-4980-8eac-1450a40af438)

We need this added to precheck and tapeout processes.

**Comment by jeffdi** [comment]
Check for klayout functionality to identify otherwise ask Risto to create a script (klayout).

**Comment by DavidRLindley** [comment]
Risto has created Klayout script to check for spikes. Plan was to release 3/12/24.  I need to get the script and run some tests.
