### ISSUE TITLE
Create illegal cell name character check in precheck and tapeout flows

### ISSUE THREAD

**Issue by DavidRLindley** [efabless/mpw_precheck#284]
'"/' and '#' have been flagged by Skywater.  Are there other illegal characters?  Should we automatically replaced with another string ('__' maybe)? Or, push back to customer?

**Comment by urish** [comment]
Looks like magic sometimes creates cells with "#". We've just hit this on Tiny Tapeout:

![image](https://github.com/user-attachments/assets/b62460a2-b90e-4a48-877b-bedc41e6cf2f)

**Comment by dlmiles** [comment]
@RTimothyEdwards 

Candidate offending cause could be auto-renaming during cell read-in by Magic VLSI tool

https://github.com/RTimothyEdwards/magic/blob/master/database/DBio.c#L2122 currently there is no config option to change suffix method renaming strategy to be compatible with this new precheck.

**Comment by DavidRLindley** [comment]
Hi Uri,

If that is the only error, just edit the user_project_wrapper.gds to
replace the illegal character with something else.  A unique number per
instance maybe. I think I used "__" in your last tapeout. Let me know once
you've done so and I'll push it into tapeout.  Hopefully we'll have a fix
before the next shuttle.

David

**Comment by urish** [comment]
Thanks David! It was @algofoogle's project, and he swiftly pushed a fix.

**Comment by urish** [comment]
I believe so - we'll retry tonight after the tt08 submission deadline

**Comment by DavidRLindley** [comment]
Alright!  Let me know if you need anything.

**Comment by DavidRLindley** [comment]
done
