### ISSUE TITLE
Documentation check not suitable

### ISSUE THREAD

**Issue by agorararmard** [efabless/mpw_precheck#4]
(This is moved from #3 for ease of traceability)

It should check the following:
- All documentation should use inclusive language https://opensource.google/docs/releasing/preparing/#inclusive
- Repository should have a README file
        https://opensource.google/docs/releasing/preparing/#include-a-readme-file

**Comment by agorararmard** [comment]
@mithro: Does that #7 resolve this?

**Comment by mithro** [comment]
Could you create some tests of example repositories which should pass and fail these documentation checks? That way it doesn't matter how the implementation is written, only that the examples look right to me.

**Comment by agorararmard** [comment]
@mithro: Briefly, until we prepare full repos of caravel test cases, what the documentation checks do currently is the following:
1. check for a top level (in the main page) README file of any txt file documentation format.
2. Reads all documentation files in all project sub-directories along with the main README file and checks for the use of the following words and their derivatives: slave, whitelist, blacklist. 

And that's about it for the documentation checks. 

Do you think we should force the inclusion of some sections with specific naming, i.e.: `How to Run` and so?

**Comment by mithro** [comment]
@agorararmard - As we only have two checks, I think it is pretty simple to create some tests which should cover the failing and passing use cases?

**Comment by mithro** [comment]
I also don't think we need to be any more strict about documentation.

**Comment by agorararmard** [comment]
> @agorararmard - As we only have two checks, I think it is pretty simple to create some tests which should cover the failing and passing use cases?

@mithro: The thing is the doc checks are part of the fuzzy checks (not a separate script) but a function within a script. However, my reply above is the result of running some local tests with some tweaks in the requirements of the other checks (the non-doc checks).

We should be able to have full caravel test cases by the end of the week. (Hopefully)

**Comment by agorararmard** [comment]
> I also don't think we need to be any more strict about documentation.

Roger that.

**Comment by mithro** [comment]
@agorararmard Each check should be tested independently?

**Comment by agorararmard** [comment]
@mithro: It was tested independently after disabling the rest of the checks (which is not the default behavior). Anyhow, what I did is that I tested on the OpenLANE repository without any changes and with adding some derivates of (slave, blacklist, whitelist) and seeing the result. I also tried deleting the main README.md file.

Each check was tested independently before the integration.

**Comment by mithro** [comment]
@agorararmard -- Manual testing is testing that does not exist. Please set up testing so it can be run by any developer and by the CI system.

**Comment by DavidRLindley** [comment]
I'm closing this ticket due to age and staleness.
